---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Debug
      debug: var=inventory_hostname

    - name: vmware drs
      vmware_drs:
        datacenter: datacenter_name
        cluster: cluster_name
        user: username
        password: password
        vm_host_a: host1
        vm_host_b: host2
