---
- hosts: localhost
  connection: local
  gather_facts: false
  ignore_errors: true

  tasks:
    - name: Debug
      debug: var=inventory_hostname

    - name: vmware drs
      vmware_drs:
        hostname: "vcenter.example.com"
        username: "username"
        password: "password"
        cluster: "cluster-name"
        name: "hosta-hostb"
        hosts:
          - "hosta"
          - "hostb"
