---
- hosts: localhost
  connection: local
  gather_facts: false
  ignore_errors: true

  vars:
    vcenter_hostname: vcenter.example.com
    vcenter_user: username
    vcenter_pass: password
    vcenter_cluster: Cluster Name
    drs_name: DRS Rule_Name
    drs_vms:
      vm-a
      vm-b

  tasks:
    - name: Debug
      debug: var=inventory_hostname

    - name: Gather facts only
      vmware_drs:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        cluster: "{{ vcenter_cluster }}"
        vms: "{{ drs_vms }}"
        gather_facts: true
        validate_certs: false
      register: results

    - name: Delete DRS rule
      vmware_drs:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        cluster: "{{ vcenter_cluster }}"
        state: absent
        name: "{{ drs_name }}"
        validate_certs: false
      register: results

    - name: Create DRS rule
      vmware_drs:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        cluster: "{{ vcenter_cluster }}"
        state: present
        name: "{{ drs_name }}"
        vms: "{{ drs_vms }}"
        keep_together: false
        validate_certs: false
      register: results
